version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies.sh
  ApplicationStart:
    - location: /scripts/start_server.sh
      timeout: 3600